version: '3.3'

services:

  frontend:
    container_name: unsplash-search
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - NODE_ENV=development
